### ISSUE TITLE
Incubator hitbox placement issue

### ISSUE THREAD

**Issue by NotThatHyper** [Dumb-Code/Project-Nublar#30]
The incubator hitbox places weirdly. Since it's 2 blocks tall, when placed against a wall, the top cube of the hitbox goes on the side (or front of the bottom hotbox). The base still has a hitbox, but the hitbox on top generates like the entire model flips when placed on the side of a cube.
![2024-08-28_02 28 32](https://github.com/user-attachments/assets/f38faed0-262b-4f29-9881-8705f581d357)

**Comment by Nyfaria** [comment]
This is not a bug, hitboxes aren't implemented yet.
