### ISSUE TITLE
Incubator chainbreaks

### ISSUE THREAD

**Issue by NotThatHyper** [Dumb-Code/Project-Nublar#31]
When placed next to eachother, incubators break when one is broken. (They have all been placed on the grass, not the side of the neighbouring incubator. In the picture below, the incubators have been placed from left to right, breaking only the second-most left incubator.
![2024-08-28_02 32 01](https://github.com/user-attachments/assets/f11ac601-c93d-4446-a217-78ffef73cb9d)
![2024-08-28_02 32 04](https://github.com/user-attachments/assets/c07e6208-9c73-4c9a-9b80-e2d4709c4029)

**Comment by HerrChaos** [comment]
also fabric
